### ISSUE TITLE
السلام عليكم

### ISSUE THREAD

**Issue by Moath** [miuiarabic/MIUI#4]
السلام عليكم ..

عشان يسهل البحث عن البقية  README  يالغالي بخصوص الملفات التي خلص تعريبها ياليت تزيلها من

**Comment by miuiarabic** [comment]
السلام عليكم ورحمة الله
ان شاء الله 

اخي معاذ 
هناك بعض الجمل في FileExplorer 
لم تتم ترجمتها
الرجاء اكمالها حتى يبقى التعديل بأسمك
لاأريد تعديلها حتى يبقى العرفان لمن قام بالعمل

**Comment by Moath** [comment]
غالبا  الجمل التي ماترجمتها ..

لم اجد الصياغة المناسبة لها ..

اذا وجدتها انت اضفها اهم شي نخرج بتعريب كامل مناسب , 

*\* هل دمجت باقي البرامج اللي عربتها اليوم ؟؟
